#!/bin/bash
# Completion script for basic Metabiome commands

_metabiome(){
word=${COMP_WORDS[COMP_CWORD]}

if [ "$COMP_CWORD" -eq 1 ]; then
		COMPREPLY=($(compgen -W "bbduk bowtie2 concoct coverm humann2 kaiju kraken2 krona maxbin2 megahit metabat2 metaphlan3 metaspades qc trimmomatic" "${word}"))
    elif [ "$3" == "-i" ] || [ "$3" == "-o" ]; then
        COMPREPLY=($(compgen -d "${word}"))
fi
}

complete -F _metabiome -o bashdefault -o filenames metabiome
